[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
defmt = "0.3.5"
embedded-hal = "0.2.7"

[features]
default = ["common/simulator"]
bearpi = ["common/bearpi"] 